# NumPy

NumPy is a powerful linear algebra library for Python. What makes it so important is that almost all of the libraries in the PyData ecosystem (pandas, scipy, scikit-learn, etc.) rely on NumPy as one of their main building blocks. Plus we will use it to generate data for our analysis examples later on!

NumPy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy. To get started we need to install it!

# Importing NumPy

Once you’ve installed NumPy you can import it as a library:

In [2]:
import numpy as np

NumPy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of NumPy: vectors, arrays, matrices and number generation. Let's start by discussing arrays.

# NumPy Arrays

NumPy arrays are the main way we will use NumPy throughout the course. NumPy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-dimensional (1D) arrays and matrices are 2D (but you should note a matrix can still have only one row or one column).

## Why use Numpy array? Why not just a list?

There are lot's of reasons to use a Numpy array instead of a "standard" python list object. Our main reasons are:
* Memory Efficiency of Numpy Array vs list
* Easily expands to N-dimensional objects
* Speed of calculations of numpy array
* Broadcasting operations and functions with numpy
* All the data science and machine learning libraries we use are built with Numpy

## Simple Example of what numpy array can do

In [9]:
a = np.array([2, 3, 4])
b = np.array([(1.5, 2,3), (4, 5, 6)])
c = np.arange(15)
d = np.arange(15).reshape(3, 5)
e = np.zeros((3, 4))
f = np.ones((2, 3, 4), dtype=np.int16)
g = np.eye(3)
h = np.random.rand(2,3)
i = h.max()
j = h.argmax()

print(a.shape, a)
print(b.shape, b)
print(c.shape, c)
print(d.shape, d)
print(e.shape, e)
print(f.shape, f)
print(g.shape, g)
print(h.shape, h)
print(i.shape, i)
print(j.shape, j)

(3,) [2 3 4]
(2, 3) [[1.5 2.  3. ]
 [4.  5.  6. ]]
(15,) [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
(3, 5) [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 4) [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 3, 4) [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(3, 3) [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(2, 3) [[0.1315285  0.40071424 0.31604984]
 [0.71608116 0.7006495  0.1121293 ]]
() 0.7160811572692115
() 3


In [14]:
# Numpy Operations
k = a * 2
l = b.sum(axis=0)
m = np.exp(c)

k.shape, k


((3,), array([4, 6, 8]))